// Write your MySQL query statement below
SELECT FIRSTNAME, LASTNAME, CITY, STATE
FROM Person LEFT JOIN Address USING (PersonId);

-- Select FIRSTNAME, LASTNAME, CITY, STATE
-- FROM PERSON LEFT JOIN ADDRESS
--     ON PERSON.PERSONID = ADDRESS.PERSONID;